apiVersion: v1
kind: Pod
metadata:
  name: just-enough-pod-v1
  labels:
    app: just-enough-web
spec:
  containers:
  - name: just-enough-container
    image: burningpony/just-enough-kubernetes:release-0.0.8
    command:
      - rackup
    args:
      - -o
      - "0.0.0.0"
    ports:
      - name: http
        containerPort: 9292
