apiVersion: v1
kind: Pod
metadata:
  name: just-enough-pod-v1
  labels:
    app: just-enough-web
spec:
  containers:
  - name: just-enough-container
    image: burningpony/just-enough-kubernetes:release-0.1.0
    command:
      - rackup
    args:
      - -o
      - "0.0.0.0"
    ports:
      - name: http
        containerPort: 9292



















    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
